### ISSUE TITLE
Updating to “linter-retextjs@0.28.0” failed.

### ISSUE THREAD

**Issue by dpo** [benmarwick/linter-retextjs#2]
Trying to update this package in Atom yields the error in the title. The output further says
```
npm ERR! code E400
npm ERR! 400 Bad Request: https://www.atom.io/api/packages/linter-retextjs/versions/0.28.0/tarball

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dpo/.atom/.apm/_logs/2019-02-06T04_23_47_811Z-debug.log
```
Here's [2019-02-06T04_23_47_811Z-debug.log](https://gist.github.com/ca8377efdd51ed5edaf67cb3787f6040).

Thanks.

**Comment by benmarwick** [comment]
I moved the GitHub repo from a fork to a fresh one so we can have an issue tracker. That seems to have broken something in apm - I could reproduce your error. So I unpublished and published again, and I think that's fixed it. Can you confirm?

**Comment by rriemann** [comment]
I installed linter-retextjs@0.31.0 with no issues and the latest version of atom.

**Comment by dpo** [comment]
Worked for me too. Thanks.
